# Generated by Django 5.0.7 on 2024-08-25 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("general_admin", "General Admin"),
                            ("classroom_admin", "Class Admin"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_last_login", models.DateTimeField(blank=True, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("email_verification_token", models.UUIDField(default=uuid.uuid4)),
                ("test", models.IntegerField()),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
    ]
