# Generated by Django 5.0.7 on 2024-08-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
