# Generated by Django 5.0.7 on 2024-08-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_users_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="test",
        ),
    ]
