# Generated by Django 5.0.7 on 2024-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_coursematerial_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="course_material_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
