# Generated by Django 5.0.7 on 2024-08-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_invitation_registration_link_sent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="registration_link_sent",
            new_name="enrolment_link_sent",
        ),
        migrations.RenameField(
            model_name="invitation",
            old_name="registration_token_expiry",
            new_name="enrolment_token_expiry",
        ),
        migrations.AddField(
            model_name="invitation",
            name="register_first",
            field=models.BooleanField(default=False),
        ),
    ]
