# Generated by Django 5.0.7 on 2024-08-28 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("long_answer", "Long Answer/Essay"),
                            ("fill_in_the_blank", "Fill-in-the-Blank"),
                        ],
                        max_length=20,
                    ),
                ),
                ("choices", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.TextField(blank=True, null=True)),
                ("points", models.IntegerField(blank=True, default=1, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="home.lesson",
                    ),
                ),
            ],
        ),
    ]
