# Generated by Django 5.0.7 on 2024-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="choices",
            field=models.TextField(blank=True, null=True),
        ),
    ]
