# Generated by Django 5.0.7 on 2024-08-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_question_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
