# Generated by Django 5.0.7 on 2024-08-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_question_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursematerial",
            name="course_material_url",
            field=models.URLField(blank=True, editable=False, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
