# Generated by Django 5.0.7 on 2024-08-28 21:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_examsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
