# Generated by Django 5.0.7 on 2024-08-29 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_focuslosslog_webcamcapture"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="session",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="home.examsession",
            ),
            preserve_default=False,
        ),
    ]
