# Generated by Django 5.0.7 on 2024-08-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_coursematerial_course_material_url_and_more"),
        ("home", "0013_examanswer_session"),
    ]

    operations = []
