# Generated by Django 5.0.7 on 2024-08-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_alter_examsubmission_submission_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examsubmission",
            name="status",
            field=models.CharField(
                choices=[("ungraded", "Ungraded"), ("graded", "Graded")],
                default="ungraded",
                max_length=20,
            ),
        ),
    ]
