# Generated by Django 5.0.7 on 2024-08-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_merge_20240829_1919"),
        ("home", "0019_alter_examsubmission_status"),
    ]

    operations = []
